project_id             = ""
region                 = ""
org_id                 = ""
project_level_roles    = ["roles/cloudfunctions.developer", "roles/pubsub.publisher", "roles/bigquery.user"]
org_level_roles        = ["roles/cloudasset.viewer", "roles/resourcemanager.organizationViewer"]
bq_dataset_level_roles = ["roles/bigquery.dataEditor"]
bq_location            = ""
service_account_name   = ""
pubsub_topic_name      = ""
cloud_scheduler_name   = ""
cloud_scheduler_cron   = ""
